config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    # Don't need doses#index as doses can be listed in #cocktail#show
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="d-flex justify-content-center">
  <h2 class="bright-shadow">Available Cocktails</h2>
</div>

<div class="card-container">
  <div class="row justify-content-center">

    <% @cocktails.each do |cocktail| %>
      <div class="col-4">
        <div class="card m-3 rounded bg-dark-lg bright-box-shadow">
          <%= cl_image_tag(cocktail.photo.key,
            width: 150, height: 150, crop: :limit, class: 'card-img-top rounded-top', style: 'height:200px') %>
          <div class="card-body text-center">
          <p class="m-0"><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<h3>New Cocktail</h3>
<%= simple_form_for @cocktail, url: cocktails_path, method: :post do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Create cocktail', class: 'btn btn-primary' %>
<% end %>

app/views/cocktails/show.html.erb
<h3><%= @cocktail.name %></h3>
<p>About: <%= @cocktail.description %></p>
<p>Ingredients:</p>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li>
      <%= "#{dose.ingredient.name}: #{dose.description}" %> |
      <%= link_to 'Delete', dose_path(dose), method: :delete, data: { confirm: 'Confirm delete?' } %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add ingredient', new_cocktail_dose_path(@cocktail) %>

app/views/doses/new.html.erb
<h3>New Ingredient</h3>
<%= simple_form_for [@cocktail, @dose], url: cocktail_doses_path, method: :post do |f| %>
  <%#= raise %>
  <%= f.association :cocktail, selected: params[:cocktail_id].to_i %>
  <%= f.input :description %>
  <%= f.association :ingredient, label_method: :name %>
  <%= f.submit 'Add ingredient', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <nav class="navbar bg-dark-lg p-3">
      <h1 class="dull-shadow m-0"><%= link_to 'Mister Cocktail', cocktails_path, class: 'text-success' %></h1>
      <%= link_to 'New Cocktail', new_cocktail_path, class: "btn btn-outline-success" %>
    </nav>

    <div class="container py-3">
      <%= yield %>
    </div>

  </body>
</html>